// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKoRhakNu624C7wYynPrZ1Q0y5brj-G6M',
    appId: '1:515311387206:web:721e4e05c3de98c5bc8047',
    messagingSenderId: '515311387206',
    projectId: 'clinicalmonitorapp',
    authDomain: 'clinicalmonitorapp.firebaseapp.com',
    storageBucket: 'clinicalmonitorapp.firebasestorage.app',
    measurementId: 'G-RM44VPEHBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIXAZOYnQKVTAzHqlZ86q0ZdlxTLDVnXg',
    appId: '1:515311387206:android:f7253aa6119207d1bc8047',
    messagingSenderId: '515311387206',
    projectId: 'clinicalmonitorapp',
    storageBucket: 'clinicalmonitorapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMjRhUZrQ7HYtXEFoqcejHBSXrwcR6ahM',
    appId: '1:515311387206:ios:dcf3835a63ae30cbbc8047',
    messagingSenderId: '515311387206',
    projectId: 'clinicalmonitorapp',
    storageBucket: 'clinicalmonitorapp.firebasestorage.app',
    iosBundleId: 'com.example.clinicalMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMjRhUZrQ7HYtXEFoqcejHBSXrwcR6ahM',
    appId: '1:515311387206:ios:dcf3835a63ae30cbbc8047',
    messagingSenderId: '515311387206',
    projectId: 'clinicalmonitorapp',
    storageBucket: 'clinicalmonitorapp.firebasestorage.app',
    iosBundleId: 'com.example.clinicalMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKoRhakNu624C7wYynPrZ1Q0y5brj-G6M',
    appId: '1:515311387206:web:5aedabdee9374bc6bc8047',
    messagingSenderId: '515311387206',
    projectId: 'clinicalmonitorapp',
    authDomain: 'clinicalmonitorapp.firebaseapp.com',
    storageBucket: 'clinicalmonitorapp.firebasestorage.app',
    measurementId: 'G-6MTCJ92XHP',
  );
}
